### ISSUE TITLE
feature: add glance as extras for news/feed hub it goes well with omarchy

### ISSUE THREAD

**Issue by al3rez** [basecamp/omarchy#14]
i've been using glance for a while and i think its' a great setup to add to omarchy for news/feed/youtube setup

we can discuss the right shorcuts on how to open it and for themes i am using tokyho night custom theme:

```
theme:
  background-color: 240 21 15
  contrast-multiplier: 1.2
  primary-color: 217 92 83
  positive-color: 115 54 76
  negative-color: 347 70 65

```

![Image](https://github.com/user-attachments/assets/51e88370-a61c-4fa0-b9b4-53c78bdb613b)

https://github.com/glanceapp/glance
